### ISSUE TITLE
Scoped services sample?

### ISSUE THREAD

**Issue by Jesus805** [dansiegel/Prism.Container.Extensions#112]
I am interested in scoping services because I have an application with multiple shells. Are there any code samples on how to use `RegisterScoped(Type)` and Resolving a scoped service?

**Comment by hippieZhou** [comment]
@Jesus805 ,maybe you can do like this:

```C#
using var scope = PrismContainerExtension.Current.Instance.CreateScope();
var dbContext = scope.ServiceProvider.GetRequiredService<ApplicationDbContext>();
```

**Comment by Jesus805** [comment]
@hippieZhou Thanks for the reply. I was under the impression that you would be able to resolve a scope or to refer to a specific scope when resolving. Maybe I'm misunderstanding the intent of this code (The Scope tutorial is listed TODO https://prismplugins.com/scoping/)

**Comment by joezhang-sh** [comment]
I want to know how to use the scoped services in "unit of work" pattern with aop.

**Comment by dansiegel** [comment]
Scoping is an advanced topic. Prism 8 will be using scoping internally for Prism.Forms. You should not control scopes at any point there. Otherwise this is only for those who do not require a sample.

Scoped Service support was added to make it easier on those who wanted to use IServiceCollection extensions such as those for IHttpClientFactory as it is registered as a Scoped Service.
