### ISSUE TITLE
Injection work in property but not in Constructor 

### ISSUE THREAD

**Issue by SalimiHabib** [dansiegel/Prism.Container.Extensions#149]
After registering services in **PrismContainerExtension.Current.RegisterServices**  Constructor injection dos'n work but object accessible in property injection by using   **PrismContainerExtension.Current** .

 `IProvisioningService  provisioningService= PrismContainerExtension.Current.Resolve<DefaultProvisioningService>();`

Registration  in ` protected override void RegisterTypes(IContainerRegistry containerRegistry)`    is  as below :
`

            PrismContainerExtension.Current.RegisterServices(services => 
            {
       
                services.AddLogging();
                services.AddHttpClient();

                services.AddAriesFramework(builder => builder.RegisterEdgeAgent(
                            options: options =>
                            {
                                options.EndpointUri = "http://localhost:5000";
                                options.AgentName = "AcoAgent";
                                options.WalletConfiguration.StorageConfiguration =
                                    new WalletConfiguration.WalletStorageConfiguration
                                    {
                                        Path = Path.Combine(
                                            path1: FileSystem.AppDataDirectory,
                                            path2: ".indy_client",
                                            path3: "wallets")
                                    };
                                options.WalletConfiguration.Id = "MobileWallet";
                                options.WalletCredentials.Key = "SecretWalletKey";
                                options.RevocationRegistryDirectory = Path.Combine(
                                    path1: FileSystem.AppDataDirectory,
                                    path2: ".indy_client",
                                    path3: "tails");

                                //Available network configurations(see PoolConfigurator.cs):
                                //   sovrin - live
                                //   sovrin - staging
                                //   sovrin - builder
                                //   bcovrin - test
                                options.PoolName = "sovrin-staging";
                            },
                            delayProvisioning: false));
                services.BuildServiceProvider();
            });

` 
And container extension created as below 
```

` protected override IContainerExtension CreateContainerExtension()
        {
            var container = new DryIoc.Container(this.CreateContainerRules());

            ShinyHost.Populate((serviceType, func, lifetime) =>
                container.RegisterDelegate(
                    serviceType,
                    _ => func(),
                     Reuse.Singleton // HACK: I know everything is singleton
                )
            );
            DryIocContainerExtension t = new DryIocContainerExtension(container);
            return t;
        }`

```
is it possible to access object in constructor injection ?

**Comment by dansiegel** [comment]
I'm not sure what on earth you're doing here, but you seem to be combining these libraries in the worst ways. The short answer is if you register something either with Shiny or Prism you should have no problem injecting them into your services whether it's resolved by Shiny or Prism

1. You should not be accessing the static instance of the ContainerExtension to be randomly registering services
1. If you're using shiny and you're trying to register things using IServiceCollection extensions then just register them in your Shiny Startup
1. If you're using the Container Extensions you probably should be using Shiny.Prism along with Prism.Forms.Extended in which case there is nothing you need to do to load the Prism Container, as Shiny Prism actually registers the services from the IServiceCollection with the container and then passes Shiny an IServiceProvider that points to itself so both Prism and Shiny use a single library rather than Allan's old hack. 
1. Alternatively as an FYI if you're a GitHub sponsor you get access to the Prism.Magician on the Sponsor Connect feed which means you don't need any of this and everything gets done for you.

To see how to do this properly please look at the sample in the Repo, or if you're interested in the Prism.Magician you can find a demo of that [here](https://github.com/dansiegel/Prism.Magician-Demo)
