### ISSUE TITLE
AddHttpClient behavior does not seems consistent.

### ISSUE THREAD

**Issue by lowrad000** [dansiegel/Prism.Container.Extensions#151]
Hi,
I am currently working on a mobile app using Xamarin and Prism. Recently, we moved to ASP.NET Core for the backend. I was trying to re-used the client packages to access our backend in the App.

I added dependencies to:
- Microsoft.Extensions.Http.Polly
- Prism.Microsoft.DepedencyInjection.Extensions

I can build and deploy the app correctly. But, it is not working as i was expecting. 

I am registering the client like this:
```cs
containerRegistry.RegisterServices(services =>
{
    services.Configure<GitHubOptions>(o => o.BaseUrl = "AnotherUrl");

    services.AddHttpClient<IGitHubClient, GitHubClient>(client => 
    {
        client.BaseAddress = new System.Uri("https://github.com/");
    });
});
```

After this, if i try to resolve an instance of a IGitHubClient
```cs
var myClient = Container.Resolve<IGitHubClient>();
```
The configuration delegate will be called and the BaseAddress will be set as expected. But, the Resolve method will fail with this exception:
`
"No service for type 'Microsoft.Extensions.Http.ITypedHttpClientFactory1[XamarinPrism.Clients.GitHubClient]' has been registered."
`

And the other side, if i don't try to resolve the instance at that point and let prism handle the navigation, create the view model, ... the instance og IGitHubClient i receive in my ViewModel is not configured using the configure delegate.

It is a bit perplexing, is it a bug? Or am i the one missing a details?

Thanks,

Here is a small project replicating the issue i am facing.
[XamarinPrism.zip](https://github.com/dansiegel/Prism.Container.Extensions/files/5278248/XamarinPrism.zip)

**Comment by dansiegel** [comment]
Thank you for the sample, I'll take a look at this as soon as I can, but it may be a bit as I'm currently engaged in completing some tasks for some of my other libraries.

**Comment by JeremyBP** [comment]
Hi @lowrad000,

I took some time to play with your sample because I had to play with HttClientFactory on my own Xam project repos.
First thing I noticed is that you referenced both Prism.DryIoc.Extensions and Prism.Microsoft.DependencyInjection.Extensions.
AFAIK, you have to choose witch one you want to work with, not both.

So I cleaned up the solution by referencing only Prism.Microsoft.DependencyInjection.Extensions from all projects.
Then I changed it like so:

```csharp
containerRegistry.RegisterServices(services =>
{
    services.Configure<GitHubOptions>(o => o.BaseUrl = "AnotherUrl");

    services.AddHttpClient("GitHubHttpClient", client =>
    {
        client.BaseAddress = new System.Uri("https://github.com/");
    }).AddTypedClient<IGitHubClient>((client, serviceProvider) =>
        new GitHubClient(client, serviceProvider.GetRequiredService<IOptions<GitHubOptions>>())); 
});
```
and this worked for me

```csharp
var gitHubClient = Container.Resolve<IGitHubClient>();
```
Don't forget to change your viewmodels constructor injected parameter to IGitHubClient type to.

I had some issues with Options pattern managed by Prism.DryIoc.Extensions v7, but no problem with Prism.Microsoft.DependencyInjection.Extensions v7. If you do need DryIoc, maybe you should give a try to v8 from SponsorConnect feed as it fix some issues, but I did not test it specifically with options pattern. On the other hand, I believe Prism.Microsoft.DependencyInjection.Extensions is quite experimental.

Hope it helped :)
