### ISSUE TITLE
IExtendedContainerRegistryExtensions.RegisterScoped NotImplementedException

### ISSUE THREAD

**Issue by veccie** [dansiegel/Prism.Container.Extensions#152]
I keep getting NotImplementedException when using the Prism.Container.Extensions package (1054). Also from the latest CI version (1115).

I'm using it with Prism.Unity (WPF) and adding HttpClient and Logging which uses scoped I presume.

This seems to be some old code/files when looking at the commit history? Why is this still in the packages?

```
at Prism.Ioc.IExtendedContainerRegistryExtensions.RegisterScoped(IContainerRegistry containerRegistry, Type serviceType, Type implementationType)
at Prism.Ioc.IServiceProviderExtensions.RegisterTypesWithPrismContainer(IContainerRegistry containerRegistry, IServiceCollection services)
at Prism.Ioc.IServiceCollectionExtensions.RegisterServices(IContainerRegistry containerRegistry, Action`1 registerServices)
```

**Comment by veccie** [comment]
Doh, just noticed that the CI builds haven't been updated since April which explains the old code.

Any plans for when the next CI build/release is?

**Comment by dansiegel** [comment]
> Doh, just noticed that the CI builds haven't been updated since April which explains the old code.
>
> Any plans for when the next CI build/release is?


@veccie the latest build was done 2 weeks ago and targets Prism 8.

Please note that all CI packages are hosted exclusively on the Sponsor Connect NuGet feed. In order to access the CI packages or get earlier access to releases you would need to be a sponsor and use that feed.

As for the NotImplementedException you haven't really provided me any sample code to reproduce your issue. That said If you're just trying to use the Prism.Container.Extensions directly with Prism.Unity it won't work, you would need to use the Prism.Unity.Extended package and then further adapt the container to work for WPF.
