### ISSUE TITLE
Prism 8

### ISSUE THREAD

**Issue by mtrainham** [dansiegel/Prism.Container.Extensions#174]
Could you please create a release that works with the new Prism 8?

I get this exception when using Prism.DryIoc.Extensions 7.2.0.1054 with Prism 8:

> System.TypeLoadException: 'Method 'CreateScope' in type 'Prism.DryIoc.PrismContainerExtension' from assembly 'Prism.DryIoc.Extensions, Version=7.2.0.1054, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by dansiegel** [comment]
if you look you'll notice one already exists on Sponsor Connect

**Comment by mtrainham** [comment]
Are you serious? We can't have a public package, we have to sponsor? This is ridiculous.

**Comment by mtrainham** [comment]
I can't upgrade my app to Prism 8 all because you choose to not publish a package you already have, publicly

**Comment by dansiegel** [comment]
I'll release it to NuGet when I'm ready... you are bitching about something I provide for free. Check your entitlement because I owe you nothing.

**Comment by mtrainham** [comment]
You don't owe me anything, but you do have some responsibility when people count on your packages in their app. Why would we choose to support your open source project in the first place if we knew down the road you were going to start charging for it. That's what is irritating. Had you done this from the start, then we could have made an informed decision whether or not to start using it.

**Comment by mtrainham** [comment]
Your one package is literally keeping me from using Prism 8, and I am only now finding out it's because you just decided to stop offering your releases for free

**Comment by mtrainham** [comment]
And just like that, that's all I needed to switch solely to reactiveui. Thanks for making the decision easy.

**Comment by dansiegel** [comment]
It's not that I'm charging.. it's still open source and I'll release a package when I'm ready to... there are still issues I want to address before releasing... frankly when I get entitled asshats like yourself that want to demand that I release something I do for free to help them on something that makes them money, all it does is make me choose not to release it as soon as I otherwise would.

**Comment by mtrainham** [comment]
I'm not being entitled. I wouldn't be upset if you hadn't provided an update because you were too busy, or you stopped working on this project. I mean that's understandable, you do this in your free time. But you literally have already created a fix for this, and are just holding out releasing it to the public. So you convinced us to start using your software under the impression it was freely available, and then all the sudden started charging for it. That's messed up.

**Comment by mtrainham** [comment]
Everything Prism related is now on to the next version, and this one package is preventing people from upgrading.

**Comment by dansiegel** [comment]
Actually I haven't released updates for the Popups either and that is by far more popular than the Container Extensions

**Comment by mtrainham** [comment]
Oh, my mistake, it's worse than I thought.

**Comment by dansiegel** [comment]
You know you could actually support the people who write the tools that help you make money and ship apps... instead you're choosing to harass people that release tools to the community for free. If you would rather spend hundreds of hours to rewrite your app because I haven't released an update for this yet, then have fun with that... I'll be sure to let the ReactiveUI team know about you.

**Comment by mtrainham** [comment]
Sounds like creating freely available software has left you bitter. It's really ironic that you chose to start making software for free and convinced people to start using it, as if you were oblivious that when people start depending on your software in production apps, they will expect maintenance and updates.

**Comment by dansiegel** [comment]
bitter no... but I don't tolerate people who want to demand I work for free for them. This is my passion I do this for the community in my own time. You aren't paying and I owe you nothing on a timeline that works for you.

**Comment by mtrainham** [comment]
I'm actually creating a small open source app to help a local pool hall run pool tournaments. I'm not making a dime off of my software. When you send the message to your users that you expect them to pay to get your releases after already making an investment in learning and using your framework, why would I not change to a truly open source framework, knowing you are going to continue doing this in the future?

**Comment by dansiegel** [comment]
if you require my CI feed than yes I do require that you help support the project. Otherwise use what's publicly and freely available. That's how open source works. But instead you choose to come over here and demand I provide you something for free. If you want to rewrite your app that's on you, have fun.
