### ISSUE TITLE
no implementation for interface method Splat.IMutableDependencyResolver::HasRegistration(Type) in class Prism.DryIoc.PrismContainerExtension

### ISSUE THREAD

**Issue by candidodmv** [dansiegel/Prism.Container.Extensions#32]
This error is raising during initalization.

**Comment by dansiegel** [comment]
this is due to Splat changing the definition of IMutableDependencyResolver. Whatever you're referencing that brings in Splat besides the container extensions will need to be brought down to a version that references what the Container Extensions do. This is already fixed in the master branch and will be part of the next release.
