### ISSUE TITLE
No assembly containing a reference to an IContainerExtension implementation could be found. You must have a reference to one of the DI Container Extensions in your final project

### ISSUE THREAD

**Issue by Rob-Houweling** [dansiegel/Prism.Container.Extensions#90]
Hi,

I had an existing Xamarin Forms project setup using PRISM and added Shiny and Prism.Shiny. When starting the (Android) app it failed with:
_No assembly containing a reference to an IContainerExtension implementation could be found. You must have a reference to one of the DI Container Extensions in your final project_
After installing the Prism.DryIoc.Extensions the error went away. Problem solved for now but felt I needed to report it here. Not sure if there are any open related issues, or did I need to RTFM better?

Using the latest stable versions:
Prism v7.2.0.1422
Shiny.Prism v7.2.0.898
Shiny 1.0.0.1182

**Comment by dansiegel** [comment]
Using Shiny.Prism assumes that you are using Prism.Forms.Extended and one of the provided containers. The containers automatically wire up which is why installing Prism.DryIoc.Extensions resolved the exception you referenced.

Using it in this fashion there is no additional setup you need to do. It's not required that you use one of the Extensions packages, but you would need to do some additional setup on your side if you wanted to use say Prism.DryIoc.Forms to be able to provide the same instance of the container between your Application and Shiny.Prism.
